### ISSUE TITLE
Show time ago the most recent commit for that branch was made

### ISSUE THREAD

**Issue by thektan** [kienD/check-this-out#5]
This gives a nice breakdown of how long ago each branch had changed made to.

Something like `(2 hours ago)`

**Comment by jwu910** [comment]
https://github.com/vutran/twas Nice lightweight package =p

**Comment by kienD** [comment]
I'm currently working on this!  I'll hope to get it out soon!

@jwu910 #shamelessplug lol.

**Comment by thektan** [comment]
Git actually has something built in for this already if you format the commits. 

`'%cr': committer date, relative`
https://git-scm.com/docs/pretty-formats
