### ISSUE TITLE
Navigation is slow when using arrow keys on the keyboard

### ISSUE THREAD

**Issue by ericyanLr** [kienD/check-this-out#6]
It is difficult to scroll up and down using keyboard arrow keys.

**Comment by revelt** [comment]
maybe it's OS issue, on mac/mbp16 the speed is all right
@ericyanLr do you still use this app and it's still slow? I see two years passed since

**Comment by ericyanLr** [comment]
Hi @revelt ,

The scroll speed issue has actually been resolved in the newer versions! 
I'll mark this old issue as closed.

Hope that helps!
